config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  get 'what-we-do' => 'static_pages#about'
  get 'who-we-are' => 'static_pages#who'
  get 'get-in-touch' => 'static_pages#contact'

  get 'terms' => 'static_pages#terms'
  get 'privacy' => 'static_pages#privacy'

  post 'contact/hiring', as: 'hiring_messages'
  post 'contact/looking', as: 'looking_messages'
  post 'contact/enquiry', as: 'enquiry_messages'

  namespace :backend, path: 'admin' do
    resources :jobs
  end

end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :job_title, presence: true

  has_one :job_status
  has_one :job_type
end

app/models/job_status.rb
class JobStatus < ActiveRecord::Base

  OPEN    = 1
  CLOSED  = 2
  PAUSED  = 3
  
  has_many :jobs
end

app/models/job_type.rb
class JobType < ActiveRecord::Base
  
  PERMANENT   = 1
  CONTRACT    = 2
  FULL_TIME   = 3
  PART_TIME   = 4
  FREELANCE   = 5
  
  has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/backend/backend_controller.rb
# Indigo backend controller
class Backend::BackendController < ApplicationController

  layout 'backend'

end

app/controllers/backend/jobs_controller.rb
module Backend
  # Jobs controller
  class JobsController < BackendController
    include JobsHelper

    def index
    end
    
    def new
      @job = Job.new
    end

    def create
      @job = Job.new(job_params)
      binding.pry
      if @job.save
        redirect_to @job
      else
        render 'new'
      end
    end

    def show
      @job = Job.find(params[:id])
      @job_status = job_status(@job)
      @job_type = job_type(@job)
    end

    private

      def job_params
        params.require(:job).permit(:job_title, :city, :post_code, :salary, :job_type_id, :company, :description, :closing_date, :job_reference, :job_status_id)
      end
  end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController

  # POST /hiring
  def hiring
    @message = HiringMessage.new(hire_message_params)

    if @message.valid?
      ContactMailer.hiring(@message).deliver_now
      render status: :created, nothing: true
    else
      render status: :unprocessable_entity, nothing: true
    end
  end

  # POST /looking
  def looking
    @message = LookingMessage.new(look_message_params)

    if @message.valid?
      ContactMailer.looking(@message).deliver_now
      render status: :created, nothing: true
    else
      render status: :unprocessable_entity, nothing: true
    end
  end

  # POST /enquiry
  def enquiry
    @message = EnquiryMessage.new(enquire_message_params)

    if @message.valid?
      ContactMailer.enquiry(@message).deliver_now
      render status: :created, nothing: true
    else
      render status: :unprocessable_entity, nothing: true
    end
  end


  private

  def hire_message_params
    params.require(:hiring_message).permit!
  end

  def look_message_params
    params.require(:looking_message).permit!
  end

  def enquire_message_params
    params.require(:enquiry_message).permit!
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index
    
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def who
  end

  def contact
    @hiring_message = HiringMessage.new
    @looking_message = LookingMessage.new
    @enquiry_message = EnquiryMessage.new
  end

  def terms
  end

  def privacy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def is_active(controller, action)
    params[:action] == action && params[:controller] == controller ? "active" : nil
  end

end

app/helpers/jobs_helper.rb
module JobsHelper
  def job_status(job)
    JobStatus.find(job.job_status_id)
  end

  def job_type(job)
    JobType.find(job.job_type_id)
  end
end

app/views/backend/jobs/_form.haml
= simple_form_for [:backend, @job], validate: true do |f|
  = f.input :job_title
  = f.input :description
  = f.input :city
  = f.input :post_code
  = f.input :salary
  = f.input :company
  = f.input :closing_date
  = f.input :job_reference
  = f.select :job_status_id, options_from_collection_for_select(JobStatus.all, :id, 'status')
  = f.select :job_type_id, options_from_collection_for_select(JobType.all, :id, 'job_type')
  = f.button :submit

app/views/backend/jobs/new.haml
= render 'form'

app/views/backend/jobs/show.haml
= @job.job_title
= @job.description
= @job.city
= @job.post_code
= @job.salary
= @job.company
= @job.closing_date
= @job.job_reference
= @job_status.status
= @job_type.job_type

app/views/layouts/_background_video.haml
= video_tag "banner-video.mp4", :autoplay => true, :loop => true, :id => "bgvid", :preload => "metadata"

app/views/layouts/_banner.html.haml
.banner
  .overlay
  .slogan
    %h1
      Behind every
      %br
      %span.bold great business
      %br are
      %span.bold great people.
  .scroll-down scroll down
  %i.material-icons.arrow-down keyboard_arrow_down
  

app/views/layouts/_footer.html.haml
%footer
  .footer-info
    .row
      .small-12.medium-4.columns
        .small-12.columns.info
          %h6 Company
          %span Indigo Recruitment Services Ltd
          %span Registered company in England and Wales
          %span
            Company number:
            = t("company_number")
          %span Registered Office: 79 Bentinck road,
          %span Newcastle Upon Tyne,
          %span NE4 6UX
          %span
            REC membership number:
            = t("rec_membership_number")
          %span
            VAT number:
            = t("vat_number")
      
      .small-12.medium-4.columns
        .small-12.columns.services
          %h6 Services
          %ul
            %li
              = link_to 'Recuitment', who_we_are_path
            %li
              = link_to 'Hiring', what_we_do_path
        .small-12.columns.legal
          %h6 Legal
          = link_to "Privacy and Cookie Policy", privacy_path
          = link_to "Terms & Conditions", terms_path


      .small-12.medium-4.columns
        .small-12.columns.contact
          %h6 Contact
          %span
            %i.fi.flaticon-phone
            = t("phone_number")
          %span
            %i.fi.flaticon-email
            = t("email")        
          %span
            %i.fi.flaticon-skype2
            = t("skype")
          = link_to "Contact", get_in_touch_path, class: "hollow button"

        .small-12.columns.social-media
          %h6 Social media
          %ul.social-icons
            %li
              %a{href: t('facebook'), target: '_blank'}
                %i.fi.flaticon-facebook
            %li
              %a{href: t('google_plus'), target: '_blank'}
                %i.fi.flaticon-google-plus
            %li
              %a{href: t('linkedin'), target: '_blank'}
                %i.fi.flaticon-linkedin

  .copyright
    .row
      .small-12.columns
        %p 
          Copyright Notice
        %p
          &copy; Indigo Recruitment Services Limited, All Rights Reserved.
        %p The content of this website is protected by the copyright laws of England and Wales and by international laws and conventions.  No content from this website may be copied, reproduced or revised without the prior written consent of Indigo Recruitment Services Limited.  Copies of content may be saved and/or printed for personal use only.

app/views/layouts/_nav.html.haml
%nav#nav.desktop-nav
  %ul
    %li.logo
      = image_tag 'indigo-logo.png'
    %li
      = link_to "Home", root_path, class: is_active('static_pages', 'home')
    %li
      = link_to "Who we are", who_we_are_path, class: is_active('static_pages', 'who')
    %li
      = link_to "What we do", what_we_do_path, class: is_active('static_pages', 'about')
    %li
      = link_to "Get in touch", get_in_touch_path, class: is_active('static_pages', 'contact')


.small-nav-top-bar
  .logo
    = image_tag 'indigo-logo.png'
  #small-nav-activator
    %i.material-icons menu
#small-nav
  %ul
    %li
      = link_to "Home", root_path, class: is_active('static_pages', 'home')
    %li
      = link_to "Who we are", who_we_are_path, class: is_active('static_pages', 'who')
    %li
      = link_to "What we do", what_we_do_path, class: is_active('static_pages', 'about')
    %li
      = link_to "Get in touch", get_in_touch_path, class: is_active('static_pages', 'contact')

app/views/layouts/_under_construction.haml
.under-construction
  .row
    .small-12.columns
      = image_tag 'exclamation'
      %h4 Our new website is currently under construction...
      %p in the meantime why not register your details with us and a member of our team will be in touch, whether you are looking for work or require a temporary workforce we are here to help.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="canonical" href="www.indigo-recruitment.co.uk">
  <title>Indigo</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
  <link href='https://fonts.googleapis.com/css?family=Lato:400,100,300,700' rel='stylesheet' type='text/css'>
  <link href='https://fonts.googleapis.com/css?family=Merriweather:400,300' rel='stylesheet' type='text/css'>
  <script type="text/javascript" src="http://www.jquery-plugins.net/FeedEK/FeedEk.min.js"></script>
  <%= csrf_meta_tags %>
  <script type="text/javascript">
  window.cookieconsent_options = {"message":"We use cookies to ensure that we give you the best experience on our website. If you continue without changing your settings, we'll assume that you are happy to receive all cookies on Our website. However, if you would like to, you can change your cookie settings at an time. For more information see our ","dismiss":"Got it!","learnMore":"Privacy and Cookie Policy","link":"http://indigo-recruitment.co.uk/privacy","theme":"dark-top"};
      </script>
      <script type="text/javascript" src="//cdnjs.cloudflare.com/ajax/libs/cookieconsent2/1.0.9/cookieconsent.min.js"></script>
</head>
<body class="<%= controller_name %> <%= action_name %>">
<%= render 'layouts/nav' %>
<div class="content">
  <%= yield %>
  <%= render "layouts/footer" %>
</div>
</body>
</html>

app/views/layouts/backend.haml
%html
  = render partial: "layouts/backend/head"

  %body
    %header
      %nav

    = yield

app/views/layouts/backend/_head.haml
%head
  %title "Backend Title"

app/views/shared/_featured_jobs.haml
.featured-jobs
  .row
    .row
      .small-12.columns
        %h2
          Featured jobs
    .row
      .jobs.small-12.columns
        .job.small-12.medium-3.small-centered.columns
          Job

app/views/shared/_sticky_social_icons.haml
.sticky-social-icons
  %a.flaticon-twitter.twitter{href: "#"}
  %a.flaticon-facebook.facebook{href: "#"}
  %a.flaticon-google.google{href: "#"}
  %a.flaticon-linkedin.linkedin{href: "#"}

app/views/static_pages/_about.haml
.home-about
  .row
    %h2.medium-12.small-centered.columns
      You're only as successful as the <span class="yellow-text">people</span> around you. That's why we only <span class="yellow-text">work</span> with the <span class="yellow-text">most talented</span>, the <span class="yellow-text">most motivated</span> and those who are eager to <span class="yellow-text">learn</span>.
    .medium-6.columns
      %p
        Like Matthew. Brick layer like no other. A self-starter who lives to learn and loves to build (and cycling to places off the beaten track). Or Nina, Microsoft certified IT technician. Troubleshooter, problem-solver, all round IT whizz (who happens to play a mean guitar).
      .buttons
        = link_to get_in_touch_path, class: 'button dark-grey' do
          Hiring?
          %span Find your next star employee
        = link_to get_in_touch_path, class: 'button yellow' do
          Hunting?
          %span find your next opportunity
    .medium-6.columns
      = image_tag "construction-workers.jpg"
          

app/views/static_pages/_about_content.haml
.services-content
  .row
    .medium-4.small-12.columns
      .image
        %h3 Let's get to work
        = image_tag "services-1.jpg" 
      %p
        You're looking for work, so we're looking for work. We'll do everything we can, to help you find a suitable placement.
      %p
        We're not talking about any old job. We're talking a job that actually makes you smile.
      %p
        Your career matters. We want to see it soar.
    .medium-4.small-12.columns
      .image
        %h3 Grow your business the right way
        = image_tag "grow.jpg"
      %p
        We've a huge pool of talent, all skilled, qualified, motivated and legally compliant.
      %p
        We take care of everything - salaries, contracts and grievances, should they arise. In short, we will manage your workforce, leaving your time, free to run your business.
      %p
        So whether you're looking for temporary, seasonal or full-time staff, we're your guys.
    .medium-4.small-12.columns
      .image
        %h3 Stay compliant every time
        = image_tag "compliance.jpg"
      %p
        We pay properly through the PAYE system - no Umbrella Companies or Personal Service Companies in sight.
      %p
        We provide pay slips - with correct tax, NI and pension contributions
      %p
        We meet all the latest HMRC legislation and employment laws – it's our business to stay on top of them all.

app/views/static_pages/_about_what_we_do.haml
= image_tag "about-bg.jpg", :class => "bg-image"

.about-header
  %h1
    Work is not just about
    %br
    %span.bold paying bills; 
    %br
    work is a big part of
    %br
    %span.bold life's adventure.

app/views/static_pages/_banner_2.haml
.banner2
  .video-overlay
  #video-wrap2
    = video_tag "banner-video.mp4", :autoplay => true, :loop => true, :id => "banner", :preload => "metadata"
  .slogan
    %h1
      Behind every great business are great people
  %i.material-icons.arrow-down keyboard_arrow_down

app/views/static_pages/_contact_form.haml
.contact-section#contact
  .row
    .medium-9.columns
      %p
        We are available by phone, email, skype and online via facebook or linkedin to answer all your questions and (bonus) we are even happy to.
      %p
        If you'd like to contact us via the website please complete the enquiry form below.
      = select_tag :form_selector, options_for_select([ "General Enquiry", "I'm looking for work", "I'm looking to hire" ]) 
      .looking.messageform
        = render partial: 'working_form'
      .hiring.messageform
        = render partial: 'hiring_form'
      .enquiry.messageform
        = render partial: 'enquiry_form'
    .medium-3.columns.side
      .contact-info
        %i.fi.flaticon-email
        = t("email")
      .contact-info
        %i.fi.flaticon-phone
        = t("phone_number")
      .contact-info
        %i.fi.flaticon-skype2
        = t("skype")

app/views/static_pages/_enquiry_form.haml
= simple_form_for @enquiry_message, validate: true do |f|
  .row
    .medium-6.columns
      = f.input :first_name, placeholder: 'John'
    .medium-6.columns
      = f.input :second_name, placeholder: 'Smith'
    .medium-12.columns
      =f.input :contact_email, placeholder: 'john.smith@example.com'
    .medium-12.columns
      =f.input :message, as: :text, placeholder: 'Type your message here'
    .medium-12.columns
      = f.input :terms_of_service, as: :boolean, label: "Your personal details will only be used to help us provide our services to you. Please tick here to confirm that you have read and agree to our #{ link_to 'Privacy and Cookie Policy', privacy_path } and our #{ link_to 'Terms and Conditions', terms_path }, which outline how we will use your data.".html_safe
    .medium-12.columns
      = f.button :submit, "Send", id: 'enquiry_button'

app/views/static_pages/_hiring_form.haml
= simple_form_for @hiring_message, validate: true do |f|
  .row
    .medium-12.columns
      = f.input :company_name, placeholder: 'Your company name'
    .medium-2.columns
      = f.input :title, placeholder: 'Mr/Mrs/Miss'
    .medium-5.columns
      = f.input :first_name, placeholder: 'John'
    .medium-5.columns
      = f.input :second_name, placeholder: 'Smith'
    .medium-6.columns
      = f.input :address_line_1, placeholder: 'First Line'
    .medium-6.columns
      = f.input :address_line_2, placeholder: 'Second Line'
    .medium-6.columns
      = f.input :city, placeholder: 'Town/City', label: false
    .medium-6.columns
      = f.input :postcode, placeholder: 'Postcode', label: false
    .medium-6.columns
      = f.input :contact_number, placeholder: '01234 567890'
    .medium-6.columns
      = f.input :contact_email, placeholder: 'john.smith@sample.com'
    .medium-6.columns
      = f.input :industry, placeholder: 'Construction'
    .medium-6.columns
      = f.input :examples_of_work, placeholder: 'Welding'
    .small-12.columns
      = f.input :terms_of_service, as: :boolean, label: "Your personal details will only be used to help us provide our services to you. Please tick here to confirm that you have read and agree to our #{ link_to 'Privacy and Cookie Policy', privacy_path } and our #{ link_to 'Terms and Conditions', terms_path }, which outline how we will use your data.".html_safe

    = f.button :submit, "Send", id: 'hiring_button'

app/views/static_pages/_home_about.haml
.home-about
  .row
    .medium-4.small-12.columns
      %h2 Header 2
    .medium-8.small-12.columns
      %p.blockquote
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam pellentesque viverra nibh eget consequat. Duis ullamcorper vestibulum enim eget maximus. Vestibulum ut velit feugiat, pharetra nisi vitae, dapibus tellus. Proin euismod dui tempus mi ultrices, ac scelerisque libero tincidunt.
  .row
    .medium-4.small-12.columns
      %h3 Header 3
      %p
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam pellentesque viverra nibh eget consequat. Duis ullamcorper vestibulum enim eget maximus. Vestibulum ut velit feugiat, pharetra nisi vitae, dapibus tellus. Proin euismod dui tempus mi ultrices, ac scelerisque libero tincidunt. Sed pharetra leo id lobortis porttitor. Vestibulum tincidunt nisi vitae ante pharetra, a maximus ante sollicitudin.
    .medium-4.small-12.columns
      %h3 Header 3
      %p
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam pellentesque viverra nibh eget consequat. Duis ullamcorper vestibulum enim eget maximus. Vestibulum ut velit feugiat, pharetra nisi vitae, dapibus tellus. Proin euismod dui tempus mi ultrices, ac scelerisque libero tincidunt. Sed pharetra leo id lobortis porttitor. Vestibulum tincidunt nisi vitae ante pharetra, a maximus ante sollicitudin.
    .medium-4.small-12.columns
      %h3 Header 3
      %p
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam pellentesque viverra nibh eget consequat. Duis ullamcorper vestibulum enim eget maximus. Vestibulum ut velit feugiat, pharetra nisi vitae, dapibus tellus. Proin euismod dui tempus mi ultrices, ac scelerisque libero tincidunt. Sed pharetra leo id lobortis porttitor. Vestibulum tincidunt nisi vitae ante pharetra, a maximus ante sollicitudin.

app/views/static_pages/_rss_feed.haml
#newsSlider
  #rssFeed

app/views/static_pages/_who_content.haml
.about-content
  .row
    .medium-7.columns
      %h3
        Maybe your organisation tried 
        %span.yellow-text hiring
        through a
        %span.yellow-text recruiter
        in the past...but it was a
        %span.yellow-text bust
        %span .

      %p
        Maybe you’re just starting out on a new business adventure...and want to make sure it booms. 
      %p
        Maybe you've run yourself ragged running to keep-up with your start-up, and need an extra pair of hands, or half a dozen, to take the edge off.
      %p
        Whatever the case may be, if you want to build your team, and surround yourself with pros -- without mucking about -- then welcome. We've been expecting you.
    .medium-5.columns
      = image_tag "man-building-a-house.jpg"
  .row.dark-bg
    .row
      .medium-7.columns
        %h3.highlight-first-letter
          Our main objective
        %p
          Flooding your organisation with talent, because behind every great business are great people. When an organisation like yours misses out on recruiting the best, well, it doesn't bear thinking about does it.
        %p
          We're not in the business of temporary fixes here. We're not into job-hopping, agency swapping or short term relationships. We're in this for keeps.
        %p
          We do recruitment right.
          %span.bold-italic Right?
        .blockquote
          %p
            We 
            %strong never
            recommend candidates, who we haven't interviewed ourselves.
          %p
            We 
            %strong never
            recommend candidates, who aren't entirely suitable or qualified
          %p
            We
            %strong never
            pay through Umbrella Companies, it's PAYE – and proper wage slips – all the way.
      .medium-5.columns
        = image_tag "metal-welding.jpg"
  .row
    .medium-7.columns
      %p
        At Indigo we're driven by raw obsession, with your story, our candidates' stories, and the story of your matchmade future. 
      %p
        You want to reach the top? You need great people around you. That’s precisely who we find -- every single day.
      %p So if you have a vacancy to fill, and don't want to spend time getting down and dirty with a brick of CVs, interviews, call-backs or any of the other specifics involved in recruiting, then do get in touch.
      %p
        We do all the legwork, so all you have to say is,
        %span.bold-italic "you're hired".
      %p
        Build a workforce of nature, without wasting time.
        = link_to 'Contact us to get started.', get_in_touch_path
    .medium-5.columns
      =image_tag "it-technician.jpg"

app/views/static_pages/_work_with.haml
.home-work
  .row
    .medium-4.columns
      %h2
        Why Work With Us
    .medium-8.columns
      .medium-6.columns.who
        %h3
          We're not the cheapest
        .subheader
          But we are honest, straight-talking and open.
      .medium-6.columns.who
        %h3
          We're not cattle farmers
        .subheader
          We match the right people to the right roles
      .medium-6.columns.who
        %h3
          We're not into job-hopping
        .subheader
          It's just not our style
      .medium-6.columns.who
        %h3
          We will learn your shoe size
        .subheader
          So your work days are the best days (isn't life too short for anything else?)

app/views/static_pages/_working_form.haml
= simple_form_for @looking_message, validate: true do |f|
  .row
    .medium-2.columns
      = f.input :title, placeholder: 'Mr/Mrs/Miss'
    .medium-5.columns
      = f.input :first_name, placeholder: 'John'
    .medium-5.columns
      = f.input :second_name, placeholder: 'Smith'
    .medium-6.columns
      = f.input :address_line_1, placeholder: 'First Line'
    .medium-6.columns
      = f.input :address_line_2, placeholder: 'Second Line'
    .medium-6.columns
      = f.input :city, placeholder: 'Town/City', label: false
    .medium-6.columns
      = f.input :postcode, placeholder: 'Postcode', label: false
    .medium-6.columns
      = f.input :contact_number, placeholder: '01234 567890'
    .medium-6.columns
      = f.input :contact_email, placeholder: 'john.smith@sample.com'
    .medium-6.columns
      = f.input :occupation, placeholder: 'Brick Layer'
    .medium-6.columns
      = f.input :type_of_work, placeholder: "Write down the type of work you're looking for", label: 'Type of work'
    .small-12.columns
      = f.input :terms_of_service, as: :boolean, label: "Your personal details will only be used to help us provide our services to you. Please tick here to confirm that you have read and agree to our #{ link_to 'Privacy and Cookie Policy', privacy_path } and our #{ link_to 'Terms and Conditions', terms_path }, which outline how we will use your data.".html_safe
    .small-12.columns
      = f.button :submit, "Send", id: 'looking_button'

app/views/static_pages/home.html.erb
<%= render 'layouts/background_video' %>
<%= image_tag "about-bg.jpg", class: "home-bg-image"%>
<%= render 'layouts/banner' %>

<%= render 'static_pages/about' %>

<%= render 'static_pages/work_with' %>

app/views/static_pages/who.haml
= render 'static_pages/about_who_we_are'
= render 'static_pages/who_content'